name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Tidy modules
        run: |
          if [ -f go.mod ]; then go mod tidy; else echo "no go.mod yet"; fi

      - name: Build
        run: |
          if [ -f go.mod ]; then go build ./...; else echo "no code yet"; fi

      - name: Test
        run: |
          if [ -f go.mod ]; then go test ./... -cover; else echo "no tests yet"; fi

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t congopay:ci . || echo "Docker build will pass once app code exists"

